// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class CostcoCompareTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void compareOneProduct() {
    driver.get("https://www.costco.ca/");
    driver.manage().window().setSize(new Dimension(1236, 718));
    driver.findElement(By.id("Home_Ancillary_0")).click();
    driver.findElement(By.linkText("Northfork Meats - Venison Tenderloin 350 g (12.3 oz) x 4 tenderloins")).click();
    driver.findElement(By.cssSelector(".mar_top")).click();
    driver.findElement(By.cssSelector(".compare-buttons-container > .primary")).click();
    js.executeScript("window.scrollTo(0,61)");
    driver.findElement(By.linkText("Remove")).click();
    assertThat(driver.findElement(By.cssSelector("h1")).getText(), is("Compare Products"));
  }
  
  @Test
  public void compareTwoProducts() {
    driver.get("https://www.costco.ca/");
    driver.manage().window().setSize(new Dimension(1236, 718));
    {
      WebElement element = driver.findElement(By.id("Home_Ancillary_0"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.id("Home_Ancillary_0")).click();
    driver.findElement(By.linkText("Northfork Meats - Venison Tenderloin 350 g (12.3 oz) x 4 tenderloins")).click();
    driver.findElement(By.cssSelector(".mar_top")).click();
    js.executeScript("window.scrollTo(0,347)");
    driver.findElement(By.id("Home_Ancillary_0")).click();
    driver.findElement(By.linkText("Gutsy Kombucha Favorites 355ml (12 fl oz) x 32 cans")).click();
    driver.findElement(By.cssSelector(".mar_top")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".compare-buttons-container > .primary"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector(".compare-buttons-container > .primary")).click();
    assertThat(driver.findElement(By.cssSelector(".compare-values-header:nth-child(2)")).getText(),
        is("Northfork Meats - Venison Tenderloin 350 g (12.3 oz) x 4 tenderloins"));
    assertThat(driver.findElement(By.cssSelector(".compare-values-header:nth-child(3)")).getText(),
        is("Gutsy Kombucha Favorites 355ml (12 fl oz) x 32 cans"));
    driver.findElement(By.linkText("Remove")).click();
    driver.findElement(By.linkText("Remove")).click();
  }
  
  @Test
  public void compareTwoProductsShow() {
    driver.get("https://www.costco.ca/");
    driver.manage().window().setSize(new Dimension(1236, 718));
    {
      WebElement element = driver.findElement(By.id("Home_Ancillary_0"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.id("Home_Ancillary_0")).click();
    driver.findElement(By.linkText("Northfork Meats - Venison Tenderloin 350 g (12.3 oz) x 4 tenderloins")).click();
    driver.findElement(By.cssSelector(".mar_top")).click();
    js.executeScript("window.scrollTo(0,347)");
    driver.findElement(By.id("Home_Ancillary_0")).click();
    driver.findElement(By.linkText("Gutsy Kombucha Favorites 355ml (12 fl oz) x 32 cans")).click();
    driver.findElement(By.cssSelector(".mar_top")).click();
    driver.findElement(By.id("minimize-text")).click();
    driver.findElement(By.id("minimize-text")).click();
    assertThat(driver.findElement(By.id("minimize-text")).getText(), is("Hide"));
    driver.findElement(By.cssSelector(".compare-buttons-container > .tertiary")).click();
  }
  
  @Test
  public void compareTwoProductsRemoveOne() {
    driver.get("https://www.costco.ca/");
    driver.manage().window().setSize(new Dimension(1236, 718));
    {
      WebElement element = driver.findElement(By.id("Home_Ancillary_0"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.id("Home_Ancillary_0")).click();
    driver.findElement(By.linkText("Northfork Meats - Venison Tenderloin 350 g (12.3 oz) x 4 tenderloins")).click();
    driver.findElement(By.cssSelector(".mar_top")).click();
    js.executeScript("window.scrollTo(0,347)");
    driver.findElement(By.id("Home_Ancillary_0")).click();
    driver.findElement(By.linkText("Gutsy Kombucha Favorites 355ml (12 fl oz) x 32 cans")).click();
    driver.findElement(By.cssSelector(".mar_top")).click();
    driver.findElement(By.cssSelector(".compare-image-container:nth-child(2) > .tertiary")).click();
    {
      List<WebElement> elements = driver
          .findElements(By.cssSelector(".compare-image-container:nth-child(2) > .tertiary"));
      assert (elements.size() == 0);
    }
    driver.findElement(By.cssSelector(".compare-buttons-container > .tertiary")).click();
  }
  
  @Test
  public void compareTwoProductsRemoveAll() {
    driver.get("https://www.costco.ca/");
    driver.manage().window().setSize(new Dimension(1236, 718));
    {
      WebElement element = driver.findElement(By.id("Home_Ancillary_0"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.id("Home_Ancillary_0")).click();
    driver.findElement(By.linkText("Northfork Meats - Venison Tenderloin 350 g (12.3 oz) x 4 tenderloins")).click();
    driver.findElement(By.cssSelector(".mar_top")).click();
    js.executeScript("window.scrollTo(0,347)");
    driver.findElement(By.id("Home_Ancillary_0")).click();
    driver.findElement(By.linkText("Gutsy Kombucha Favorites 355ml (12 fl oz) x 32 cans")).click();
    driver.findElement(By.cssSelector(".mar_top")).click();
    driver.findElement(By.cssSelector(".compare-buttons-container > .tertiary")).click();
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".remove"));
      assert (elements.size() == 0);
    }
  }
  
  @Test
  public void compareTwoProductsHide() {
    driver.get("https://www.costco.ca/");
    driver.manage().window().setSize(new Dimension(1236, 718));
    {
      WebElement element = driver.findElement(By.id("Home_Ancillary_0"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.id("Home_Ancillary_0")).click();
    driver.findElement(By.linkText("Northfork Meats - Venison Tenderloin 350 g (12.3 oz) x 4 tenderloins")).click();
    driver.findElement(By.cssSelector(".mar_top")).click();
    js.executeScript("window.scrollTo(0,347)");
    driver.findElement(By.id("Home_Ancillary_0")).click();
    driver.findElement(By.linkText("Gutsy Kombucha Favorites 355ml (12 fl oz) x 32 cans")).click();
    driver.findElement(By.cssSelector(".mar_top")).click();
    driver.findElement(By.id("minimize-text")).click();
    assertThat(driver.findElement(By.id("minimize-text")).getText(), is("Show"));
    driver.findElement(By.id("minimize-text")).click();
    driver.findElement(By.cssSelector(".compare-buttons-container > .tertiary")).click();
  }
}
