// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class SearchforProductTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  
  @After
  public void tearDown() {
    driver.quit();
  }
  
  @Test
  public void searchforProductValidInput() {
    driver.get("https://www.costco.ca/");
    driver.manage().window().setSize(new Dimension(671, 850));
    driver.findElement(By.id("search-field")).click();
    driver.findElement(By.id("search-field")).sendKeys("tent");
    driver.findElement(By.cssSelector(".btn:nth-child(4) > .co-search-thin")).click();
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".product:nth-child(1) .img-responsive"));
      assert(elements.size() > 0);
    }
    driver.findElement(By.cssSelector(".product:nth-child(1) .img-responsive")).click();
    {
      List<WebElement> elements = driver.findElements(By.id("RICHFXViewerContainer___richfx_id_0_initialImage"));
      assert(elements.size() > 0);
    }
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".product-title"));
      assert(elements.size() > 0);
    }
  }
  
  @Test
  public void searchforProductNoInput() {
    driver.get("https://www.costco.ca/");
    driver.manage().window().setSize(new Dimension(695, 864));
    driver.findElement(By.cssSelector(".btn:nth-child(4) > .co-search-thin")).click();
    {
      List<WebElement> elements = driver.findElements(By.cssSelector("html"));
      assert(elements.size() > 0);
    }
  }
  
}
