// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class SignInTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void signInInvalidCredential() {
    driver.get("https://www.costco.ca/");
    driver.manage().window().setSize(new Dimension(999, 729));
    driver.findElement(By.cssSelector("#myaccount-react-t > .top-button-title")).click();
    driver.findElement(By.id("signInName")).click();
    driver.findElement(By.id("signInName")).sendKeys("marrya251@gmail.com");
    driver.findElement(By.id("password")).click();
    driver.findElement(By.id("password")).sendKeys("password");
    driver.findElement(By.id("next")).click();
    assertThat(driver.findElement(By.cssSelector(".pageLevel > p")).getText(), is("We can\\\'t seem to find your account"));
    driver.close();
  }
  @Test
  public void signInValidCredential() {
    driver.get("https://www.costco.ca/");
    driver.manage().window().setSize(new Dimension(999, 729));
    driver.findElement(By.cssSelector("#myaccount-react-t > .top-button-title")).click();
    driver.findElement(By.id("signInName")).click();
    driver.findElement(By.id("signInName")).sendKeys("marrya251@gmail.com");
    driver.findElement(By.id("password")).click();
    driver.findElement(By.id("password")).sendKeys("password");
    driver.close();
  }
}
