/**
 * Maarya Ahmed
 * COSTCO Website
 * Sign Up Page
 * Group 6
 * SENG 438 - Winter 2023
 * March 16, 2023
 */

// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class SignUpPageTestTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void signUpPageTest() {
    driver.get("https://signin.costco.com/e0714dd4-784d-46d6-a278-3e29553483eb/B2C_1A_SSO_WCS_signup_signin_537/oauth2/v2.0/authorize?ClientName=CABC&ui_locales=en-CA&scope=openid+offline_access&response_type=code+id_token&redirect_uri=https%3A%2F%2Fwww.costco.ca%2FOAuthLogonCmd&state=URL%3D%5BSSO%5D%2F%5BSSO%5D&nonce=MjnH38z5LLDfPt1s&client_id=e442e6e6-2602-4a39-937b-8b28b4457ed3&TC=0&response_mode=form_post");
    driver.manage().window().setSize(new Dimension(1215, 822));
    {
      List<WebElement> elements = driver.findElements(By.id("signInName"));
      assert(elements.size() > 0);
    }
    driver.findElement(By.id("signInName")).sendKeys("maarya251@gmail.com");
    {
      List<WebElement> elements = driver.findElements(By.id("password"));
      assert(elements.size() > 0);
    }
    driver.findElement(By.id("password")).click();
    driver.findElement(By.id("password")).sendKeys("password123");
    driver.findElement(By.cssSelector(".material-icons")).click();
    driver.findElement(By.id("next")).click();
  }
}
